name: Game of life testing

on: push

jobs:
  game-of-life-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven 3.8.2
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Show Java version
        run: java -version

      - name: Show Maven version
        run: mvn --version

      - name: Run tests
        run: mvn test

